added solutions
engineer027/Dao_3 pull request #2
Opened 2021-01-12 18:25 UTC by engineer027

2021-01-12 19:33 UTC, sanek98cv approved these changes

2021-01-13 11:28 UTC, Sofasmile requested changes

2021-01-13 11:28 UTC, Sofasmile commented on src/main/java/mate/academy/dao/impl/CarDaoImpl.java
> +        List<Car> cars = new ArrayList<>();
як варіант можна спробувати зробити це за допомогою стрімів

2021-01-13 11:28 UTC, Sofasmile commented on src/main/java/mate/academy/model/Car.java
> +    public void setDrivers(Driver driver) {
давай повернемо до попереднього вигляду) А якщо хочеш, то можна додати окремий метод щоб додавати по одній машині, але в цьому немає особливого сенсу, адже ми це можемо робити на рівні сервісу

2021-01-13 11:28 UTC, Sofasmile commented on src/main/java/mate/academy/service/mpl/CarServiceImpl.java
> +        car.getDrivers().add(driver);
варто викликати метод update для машини для того щоб зміни порапили в БД

2021-01-13 11:28 UTC, Sofasmile commented on src/main/java/mate/academy/service/mpl/CarServiceImpl.java
> +        car.getDrivers().removeIf(p -> p.equals(driver));
the same here

2021-01-13 11:28 UTC, Sofasmile commented on src/main/java/mate/academy/service/mpl/CarServiceImpl.java
> +        car.getDrivers().removeIf(p -> p.equals(driver));
```suggestion
        car.getDrivers().remove(driver);
```

2021-01-13 11:35 UTC, engineer027 commented on src/main/java/mate/academy/dao/impl/CarDaoImpl.java
> +        List<Car> cars = new ArrayList<>();
Бодя говорив на лекціїї, що якщо цикл в циклі то краще використовувати for

2021-01-13 14:46 UTC, Sofasmile approved these changes

2021-01-13 14:52 UTC, merged