Hw dao6
engineer027/Dao_3 pull request #4
Opened 2021-01-17 11:00 UTC by engineer027

2021-01-18 14:36 UTC, RuslanIbIsh requested changes

2021-01-18 14:36 UTC, RuslanIbIsh commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +                car.setId(resultSet.getLong(1));
в задании предлагают использовать getObject(name, Long.class)

2021-01-18 14:36 UTC, RuslanIbIsh commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +            for (Driver driver : car.getDrivers()) {
в задании или в чеклисте есть условие, что нужно сначала стереть всех водителей из cars_drivers, а потом записать

2021-01-18 14:36 UTC, RuslanIbIsh commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        String query = "UPDATE cars SET delete_car = ? "
```suggestion
        String query = "UPDATE cars SET delete_car = true "
```

2021-01-18 14:36 UTC, RuslanIbIsh commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +                + "AND delete_car = FALSE";
в условиях к заданию есть упоминание что нужно проверять и drivers and cars - deleted or not

2021-01-18 14:36 UTC, RuslanIbIsh commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +    private void removeDriverFromCar(Car car) {
у тебя в методе удаляются несколько драйверов - а метод имеет название про одного драйвера

2021-01-18 14:41 UTC, engineer027 commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +            for (Driver driver : car.getDrivers()) {
я це і роблю на 87 ст за допомогою removeDriverFromCar(car)

2021-01-18 14:53 UTC, RuslanIbIsh approved these changes

2021-01-18 20:29 UTC, KseniiaMakarova requested changes

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +                                          `delete_driver` TINYINT NOT NULL DEFAULT 0,
```suggestion
                                          `id` BIGINT NOT NULL,
                                          `name` VARCHAR(225) NOT NULL,
                                          `licence` VARCHAR(225) NOT NULL,
                                          `delete` TINYINT NOT NULL DEFAULT 0,
```
same for `manufacturer` and `car` tables - don't repeat the table name in columns

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +    CHANGE COLUMN `id_driver` `id_driver` BIGINT NOT NULL AUTO_INCREMENT ;
let's put here the create table statements that are correct from the start

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +                                       UNIQUE INDEX `carscol_UNIQUE` (`model_car` ASC) VISIBLE,
why is model unique?

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +    RENAME TO  `taxi_service`.`cars_drivers` ;
remove this and put to this file correct create statements

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/DriverDaoJdbc.java
> +                return Optional.of(createDriver(resultSet)); // cndjhbnb
remove the comment

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/DriverDaoJdbc.java
> +        String query = "UPDATE drivers SET delete_driver = ? "
```suggestion
        String query = "UPDATE drivers SET delete_driver = TRUE "
```

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/DriverDaoJdbc.java
> +        Long idDriver = resultSet.getObject("id_driver", long.class);
```suggestion
        Long idDriver = resultSet.getObject("id_driver", Long.class);
```

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +
redundant empty line

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +                + "JOIN manufacturer ON cars.manufacturer_id = manufacturer.id_manufacturer "
```suggestion
                + "FROM cars c "
                + "JOIN manufacturer m ON c.manufacturer_id = m.id_manufacturer "
```
use aliases

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        }
```suggestion
        Car car = null;
        try (Connection connection = ConnectionUtil.getConnection();
                PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setLong(1, id);
            ResultSet resultSet = statement.executeQuery();
            if (resultSet.next()) {
                car = createCar(resultSet);
            }
        } catch (SQLException e) {
            throw new DataProcessingException("Could not get car by id " + id, e);
        }
        if (car != null) {
            // get drivers of the car in a separate method that opens a separate connection
        }
        return Optional.ofNullable(car);
```

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        }
same for this method

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +            }
same for this method

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +                + "AND delete_driver = FALSE "
should we join `drivers` to have access to `delete_driver` column?

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        }
```suggestion
        try (Connection connection = ConnectionUtil.getConnection();
                PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setString(1, car.getModel());
            statement.setLong(2, car.getManufacturer().getId());
            statement.setLong(3, car.getId());
            statement.executeUpdate();
        } catch (SQLException e) {
            throw new DataProcessingException("Could update car " + car, e);
        }
        deleteAllDriversFromCar(car);
        addDriversToCar(car);
        return car;
```

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +            statement.setLong(1, car.getId());
```suggestion
    private void addDriverToCar(Car car) {
        String query = "INSERT INTO cars_drivers (id_car, id_driver) VALUES (?, ?);";
        try (Connection connection = ConnectionUtil.getConnection();
                PreparedStatement statement = connection.prepareStatement(query)) {
                
            // for each driver: 
            statement.setLong(1, car.getId());
            ...
```
let's not open connections in a loop, we can execute statement multiple times in one connection instead

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        car.setDrivers(getDriversForCar(idCar));
```suggestion
```
let's not open a new connection inside the existing one

2021-01-18 20:29 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +                + "WHERE cars_drivers.id_car = ?";
use aliases and check that driver is not deleted

2021-01-19 09:50 UTC, KseniiaMakarova requested changes

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +                                          UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
let's not make the driver's name unique

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/resources/init_db.sql
> +    CHANGE COLUMN `id` `id` BIGINT NOT NULL AUTO_INCREMENT ;
let's put in this file the `CREATE TABLE` statements that are correct from the start

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +                + "AND cars.deleted = FALSE";
```suggestion
        String query = "SELECT c.id, c.model, c.manufacturer_id, "
                + "m.name, m.country "
                + "FROM cars c "
                + "JOIN manufacturer m ON c.manufacturer_id = m.id "
                + "WHERE c.id = ? "
                + "AND c.deleted = FALSE";
```

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +                + "WHERE cars.deleted = FALSE";
same here

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        if (cars.size() > 0) {
do we need this check?

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +            getDriversForCar(car.getId());
let's set the drivers to car, now we just get them

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +                getDriversForCar(car.getId());
same

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +                + "AND cars.deleted = FALSE";
```suggestion
        String query = "SELECT c.id, c.model, c.manufacturer_id, "
                + "m.name, m.country "
                + "FROM cars c "
                + "JOIN cars_drivers cd ON c.id = cd.id_car "
                + "JOIN manufacturer m ON c.manufacturer_id = m.id "
                // join drivers
                + "WHERE cd.id_driver = ? "
                + "AND c.deleted = FALSE 
                // AND the driver is not deleted";
```

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        }
should we fill the cars with drivers?

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +    private void addDriverToCar(Car car) {
```suggestion
    private void addDriversToCar(Car car) {
```

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        String query = "DELETE FROM `cars_drivers` WHERE id_car = ?";
```suggestion
        String query = "DELETE FROM cars_drivers WHERE id_car = ?";
```

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        Long idCar = resultSet.getObject("id", long.class);
```suggestion
        Long idCar = resultSet.getObject("id", Long.class);
```

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +        Long manufacturerIdCar = resultSet.getObject("manufacturer_id", long.class);
same everywhere - we need wrapper, not a primitive

2021-01-19 09:50 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +                + "WHERE cd.id_car = ?";
```suggestion
        String query = "SELECT d.name_driver, d.licence_number, "
                + "cd.id_driver "
                + "FROM cars_drivers cd "
                + "JOIN drivers d ON cd.id_driver = d.id "
                + "WHERE cd.id_car = ?"
                // and driver is not deleted;
```

2021-01-19 11:26 UTC, KseniiaMakarova requested changes

2021-01-19 11:26 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +
redundant empty line

2021-01-19 11:26 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
>                  + "JOIN manufacturer m ON c.manufacturer_id = m.id "
we should join drivers as well and check that driver is not deleted

2021-01-19 11:26 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
>                  + "WHERE cd.id_car = ?";
we should check that driver is not deleted

2021-01-19 12:07 UTC, KseniiaMakarova approved these changes

2021-01-19 12:07 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/jdbc/CarDaoJdbc.java
> +                + "WHERE cd.id_car = ? AND d.beleted = FALSE";
beleted -> deleted

2021-01-19 12:11 UTC, merged