DAO_09
engineer027/Dao_3 pull request #7
Opened 2021-01-21 11:18 UTC by engineer027

1. create a new package:
cars;
drivers;
manufacturers.
2. Sorted all my Controllers.

2021-01-22 09:57 UTC, Ketch92 requested changes

2021-01-22 09:57 UTC, Ketch92 commented on src/main/java/mate/academy/controllers/cars/AddDriverToCarController.java
> +package mate.academy.controllers.cars;
the packages should have a singular naming "controllers -> controller", cars -> cars

2021-01-22 09:57 UTC, Ketch92 commented on src/main/java/mate/academy/controllers/drivers/DeleteDriverController.java
> +package mate.academy.controllers.drivers;
the same

2021-01-22 09:57 UTC, Ketch92 commented on src/main/java/mate/academy/security/AuthenticationServiceImpl.java
> +    private DriverService driverService;
I'm not sure if we need to inject a service into another service. I think there should be DriverDao. just FYI, I don't demand this change

2021-01-22 09:57 UTC, Ketch92 commented on src/main/java/mate/academy/service/DriverService.java
> +    Optional<Driver> findByLogin(String login);
If I'm right and we should inject the dao to AuthenticationService then service should return Driver and not Optional of Driver

2021-01-22 09:57 UTC, Ketch92 commented on src/main/java/mate/academy/web/filters/AuthenticationFilter.java
> +        }
check common mistakes, you can do it with single if construction

2021-01-22 11:17 UTC, Ketch92 approved these changes

2021-01-25 16:58 UTC, Sofasmile requested changes

2021-01-25 16:58 UTC, Sofasmile commented on src/main/java/mate/academy/model/Driver.java
>      public boolean equals(Object o) {
let's add login and password to equals and hashcode

2021-01-25 16:58 UTC, Sofasmile commented on src/main/java/mate/academy/security/AuthenticationServiceImpl.java
> +        Driver driverFromDB = driverDao.findByLogin(login)
Read about it in the Slack)

2021-01-26 07:55 UTC, Sofasmile requested changes

2021-01-26 07:55 UTC, Sofasmile commented on src/main/java/mate/academy/security/AuthenticationService.java
> +    Optional<Driver> login(String login, String password) throws AuthenticationException;
```suggestion
    Driver login(String login, String password) throws AuthenticationException;
```

2021-01-26 07:55 UTC, Sofasmile commented on src/main/java/mate/academy/security/AuthenticationServiceImpl.java
>              return driverFromDB;
```suggestion
    public Driver login(String login, String password) throws AuthenticationException {
        Optional<Driver> driverFromDB = driverDao.findByLogin(login);
        if (driverFromDB.isPresent() && driverFromDB.get().getPassword().equals(password)) {
            return driverFromDB.get();
```

2021-01-26 09:16 UTC, Sofasmile approved these changes

2021-02-24 19:46 UTC, merged